server:
  port: 8032
spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        -id : CITIZEN-SERVER/Vaccination-Center
        uri: //CITIZEN-SERVER//Vaccination-Center
#          lb: //CITIZEN-SERVER
      predicate:
        path: /citizen/**/vaccination-Center/**

